### ISSUE TITLE
Proxy argument

### ISSUE THREAD

**Issue by Foxtrod89** [ScribeSavant/5sim-python#2]
You didn't mention new _proxy_ argument for FiveSim

**Comment by ScribeSavant** [comment]
[Commit](https://github.com/ScribeSavant/5sim-python/commit/ec63b18d9a7023c5c1dbf7b5add156f1c6adb4f7) Now it's optional argument. Sorry for that

**Comment by Foxtrod89** [comment]
Can you provide scheme for auth proxy?

**Comment by ScribeSavant** [comment]
> snippet for **auth SOCKS5 proxies**
> 
> ```
> proxies = {
>         'http': f"socks5://{PROXY_LOGIN}:{PROXY_PASS}@{PROXY_HOST}:{PROXY_PORT}",
> } 
> ```

Add a pull request.
